services:
  db:
    image: 'postgres:17'
    container_name: auth_db
    environment:
      - 'POSTGRES_DB=auth'
      - 'POSTGRES_PASSWORD=ilya'
      - 'POSTGRES_USER=ilya'
    ports:
      - '5402:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auth
      SPRING_DATASOURCE_USERNAME: ilya
      SPRING_DATASOURCE_PASSWORD: ilya
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SERVER_PORT: "8082"

volumes:
  db_data:
